
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETE_CIERRE = 21;
  public static final int GUION = 28;
  public static final int MULTIPLICACION = 11;
  public static final int CADENA = 19;
  public static final int LETRA = 16;
  public static final int CHAR = 7;
  public static final int FIN_DECLARACION = 4;
  public static final int DECIMAL = 15;
  public static final int PARENTESIS_CIERRE = 23;
  public static final int DIVISION = 12;
  public static final int SUMA = 9;
  public static final int MAYORQUE = 27;
  public static final int PARENTESIS_APERTURA = 22;
  public static final int MODULO = 13;
  public static final int DOS_PUNTOS = 24;
  public static final int COMA = 29;
  public static final int ID_ARRAY = 18;
  public static final int EOF = 0;
  public static final int MENORQUE = 26;
  public static final int CORCHETE_APERTURA = 20;
  public static final int error = 1;
  public static final int PUNTO_COMA = 25;
  public static final int ID_VAR = 17;
  public static final int FIN_CODIGO = 3;
  public static final int ENTERO = 14;
  public static final int ARRAY = 8;
  public static final int INICIO_CODIGO = 2;
  public static final int VAR = 5;
  public static final int RESTA = 10;
  public static final int DOUBLE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_CODIGO",
  "FIN_CODIGO",
  "FIN_DECLARACION",
  "VAR",
  "DOUBLE",
  "CHAR",
  "ARRAY",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "ENTERO",
  "DECIMAL",
  "LETRA",
  "ID_VAR",
  "ID_ARRAY",
  "CADENA",
  "CORCHETE_APERTURA",
  "CORCHETE_CIERRE",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "MENORQUE",
  "MAYORQUE",
  "GUION",
  "COMA"
  };
}

